apiVersion: v1
kind: Service
metadata:
  name: myjavaapp-svc
  labels:
    app: myjavaapp
    version: 2.7.04
spec:
  type: NodePort
  ports:
  - port: 8080
    nodePort: 30004
    protocol: TCP
  selector:
    app: myjavaapp
    version: 2.7.04