apiVersion: v1
kind: ReplicationController
metadata:
  name: myjavaapp-rc
spec:
  replicas: 2
  selector:
    app: myjavaapp
    version: 2.7.04
  template:
    metadata:
      labels:
        app: myjavaapp
        version: 2.7.04
    spec:
      containers:
      - name: myjavaapp-container
        image: kartheekadev/raju:6
        ports:
        - containerPort: 8080