apiVersion: apps/v1
kind: Deployment
metadata:
  name: myjavaapp-deploy
spec:
  replicas: 2
  selector:
    matchLabels:
      app: myjavaapp
      version: 2.7.1
  minReadySeconds: 10
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  template:
    metadata:
      labels:
        app: myjavaapp
        version: 2.7.1
    spec:
      containers:
      - name: myjavaapp-pod
        image: karheekadev/kartheeka:3
        ports:
        - containerPort:  8080
          protocol: TCP